-- Add four more South African grocery chains (Woolworths, Shoprite, Spar, Food Lover's Market)
-- alongside the existing Checkers and Pick n Pay data, spanning premium to budget pricing.
with ing as (
  insert into public.ingredients (name, unit, category, price, store) values
    ('Eggs', 'dozen', 'Dairy', 54.99, 'Woolworths'),
    ('Milk', 'liter', 'Dairy', 26.99, 'Woolworths'),
    ('Bread', 'loaf', 'Bakery', 24.99, 'Woolworths'),
    ('Chicken Breast', 'kg', 'Meat', 119.99, 'Woolworths'),
    ('Rice', 'kg', 'Grains', 32.99, 'Woolworths'),
    ('Black Beans', 'can', 'Canned Goods', 21.99, 'Woolworths'),
    ('Frozen Broccoli', 'bag', 'Frozen', 44.99, 'Woolworths'),
    ('Pasta', 'packet', 'Grains', 26.99, 'Woolworths'),
    ('Tomato Sauce', 'jar', 'Canned Goods', 29.99, 'Woolworths'),
    ('Cheddar Cheese', 'block', 'Dairy', 99.99, 'Woolworths'),
    ('Peanut Butter', 'jar', 'Pantry', 47.99, 'Woolworths'),
    ('Bananas', 'kg', 'Produce', 24.99, 'Woolworths'),
    ('Oats', 'box', 'Grains', 42.99, 'Woolworths'),
    ('Beef Mince', 'kg', 'Meat', 139.99, 'Woolworths'),
    ('Onion', 'kg', 'Produce', 22.99, 'Woolworths'),
    ('Eggs', 'dozen', 'Dairy', 39.99, 'Shoprite'),
    ('Milk', 'liter', 'Dairy', 19.99, 'Shoprite'),
    ('Bread', 'loaf', 'Bakery', 16.99, 'Shoprite'),
    ('Chicken Breast', 'kg', 'Meat', 84.99, 'Shoprite'),
    ('Rice', 'kg', 'Grains', 21.99, 'Shoprite'),
    ('Black Beans', 'can', 'Canned Goods', 14.99, 'Shoprite'),
    ('Frozen Broccoli', 'bag', 'Frozen', 32.99, 'Shoprite'),
    ('Pasta', 'packet', 'Grains', 17.99, 'Shoprite'),
    ('Tomato Sauce', 'jar', 'Canned Goods', 20.99, 'Shoprite'),
    ('Cheddar Cheese', 'block', 'Dairy', 74.99, 'Shoprite'),
    ('Peanut Butter', 'jar', 'Pantry', 34.99, 'Shoprite'),
    ('Bananas', 'kg', 'Produce', 17.99, 'Shoprite'),
    ('Oats', 'box', 'Grains', 30.99, 'Shoprite'),
    ('Beef Mince', 'kg', 'Meat', 104.99, 'Shoprite'),
    ('Onion', 'kg', 'Produce', 15.99, 'Shoprite'),
    ('Eggs', 'dozen', 'Dairy', 45.99, 'Spar'),
    ('Milk', 'liter', 'Dairy', 22.99, 'Spar'),
    ('Bread', 'loaf', 'Bakery', 19.99, 'Spar'),
    ('Chicken Breast', 'kg', 'Meat', 99.99, 'Spar'),
    ('Rice', 'kg', 'Grains', 25.99, 'Spar'),
    ('Black Beans', 'can', 'Canned Goods', 17.99, 'Spar'),
    ('Frozen Broccoli', 'bag', 'Frozen', 37.99, 'Spar'),
    ('Pasta', 'packet', 'Grains', 20.99, 'Spar'),
    ('Tomato Sauce', 'jar', 'Canned Goods', 25.99, 'Spar'),
    ('Cheddar Cheese', 'block', 'Dairy', 89.99, 'Spar'),
    ('Peanut Butter', 'jar', 'Pantry', 40.99, 'Spar'),
    ('Bananas', 'kg', 'Produce', 20.99, 'Spar'),
    ('Oats', 'box', 'Grains', 35.99, 'Spar'),
    ('Beef Mince', 'kg', 'Meat', 119.99, 'Spar'),
    ('Onion', 'kg', 'Produce', 18.99, 'Spar'),
    ('Eggs', 'dozen', 'Dairy', 44.99, 'Food Lover''s Market'),
    ('Milk', 'liter', 'Dairy', 22.99, 'Food Lover''s Market'),
    ('Bread', 'loaf', 'Bakery', 19.99, 'Food Lover''s Market'),
    ('Chicken Breast', 'kg', 'Meat', 92.99, 'Food Lover''s Market'),
    ('Rice', 'kg', 'Grains', 24.99, 'Food Lover''s Market'),
    ('Black Beans', 'can', 'Canned Goods', 16.99, 'Food Lover''s Market'),
    ('Frozen Broccoli', 'bag', 'Frozen', 33.99, 'Food Lover''s Market'),
    ('Pasta', 'packet', 'Grains', 19.99, 'Food Lover''s Market'),
    ('Tomato Sauce', 'jar', 'Canned Goods', 23.99, 'Food Lover''s Market'),
    ('Cheddar Cheese', 'block', 'Dairy', 82.99, 'Food Lover''s Market'),
    ('Peanut Butter', 'jar', 'Pantry', 38.99, 'Food Lover''s Market'),
    ('Bananas', 'kg', 'Produce', 16.99, 'Food Lover''s Market'),
    ('Oats', 'box', 'Grains', 33.99, 'Food Lover''s Market'),
    ('Beef Mince', 'kg', 'Meat', 107.99, 'Food Lover''s Market'),
    ('Onion', 'kg', 'Produce', 14.99, 'Food Lover''s Market')
  returning id, name, store
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, quantity)
select r.id, i.id, v.quantity
from (values
  ('Scrambled Eggs & Toast', 'Eggs', 0.5),
  ('Scrambled Eggs & Toast', 'Bread', 0.25),
  ('Scrambled Eggs & Toast', 'Milk', 0.2),
  ('Chicken & Rice Bowl', 'Chicken Breast', 0.75),
  ('Chicken & Rice Bowl', 'Rice', 0.5),
  ('Chicken & Rice Bowl', 'Onion', 0.25),
  ('Black Bean Pasta', 'Pasta', 1),
  ('Black Bean Pasta', 'Black Beans', 2),
  ('Black Bean Pasta', 'Tomato Sauce', 1),
  ('Black Bean Pasta', 'Cheddar Cheese', 0.25),
  ('PB Banana Oats', 'Oats', 0.2),
  ('PB Banana Oats', 'Peanut Butter', 0.1),
  ('PB Banana Oats', 'Bananas', 0.3),
  ('PB Banana Oats', 'Milk', 0.2),
  ('Beef & Broccoli Stir Fry', 'Beef Mince', 0.5),
  ('Beef & Broccoli Stir Fry', 'Frozen Broccoli', 1),
  ('Beef & Broccoli Stir Fry', 'Rice', 0.5),
  ('Beef & Broccoli Stir Fry', 'Onion', 0.25)
) as v(recipe_name, ingredient_name, quantity)
join public.recipes r on r.name = v.recipe_name
join ing i on i.name = v.ingredient_name;
